# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterField.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        Form.setStyleSheet("""
                QWidget {
                background-color: #1b1b1b;
                color: #ffffff;
                font-family: 'Segoe UI', sans-serif;
                font-size: 14pt;
                }
                QLineEdit {
                background-color: #2c2c2c;
                border: 1px solid #444;
                border-radius: 8px;
                padding: 8px;
                color: #eee;
                }
                QPushButton {
                background-color: #6a5acd;
                color: white;
                border-radius: 8px;
                padding: 10px;
                font-weight: bold;
                }
                QPushButton:hover {
                background-color: #7b68ee;
                }
                QPushButton:pressed {
                background-color: #483d8b;
                }
                QLabel {
                color: #cccccc;
                }
        """)

        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(0, 50, 400, 60))
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setText("Регистрация")
        self.title_label.setStyleSheet("font-size: 26px; font-weight: bold; color: #6a5acd;")

        self.username_input = QtWidgets.QLineEdit(Form)
        self.username_input.setGeometry(QtCore.QRect(50, 150, 300, 40))
        self.username_input.setPlaceholderText("Имя пользователя")

        self.password_input = QtWidgets.QLineEdit(Form)
        self.password_input.setGeometry(QtCore.QRect(50, 220, 300, 40))
        self.password_input.setPlaceholderText("Пароль")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)

        self.register_btn = QtWidgets.QPushButton(Form)
        self.register_btn.setGeometry(QtCore.QRect(100, 320, 200, 50))
        self.register_btn.setText("Зарегистрироваться")

        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setGeometry(QtCore.QRect(100, 400, 200, 40))
        self.back_btn.setText("⬅️ Назад")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title.setText(_translate("Form", "Wallet"))
        self.Cont.setText(_translate("Form", "Зарегестрироваться"))
        self.label.setText(_translate("Form", "Введите название кошелька"))
        self.Back.setText(_translate("Form", "Вернуться"))
        self.label_2.setText(_translate("Form", "Придумайте пароль"))
